// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/login": {
            "post": {
                "description": "Api to login rock platform with name and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AUTH"
                ],
                "summary": "Login rock platform with name and password",
                "parameters": [
                    {
                        "description": "JSON type input body",
                        "name": "input_body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.LoginUserInfo"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.UserDetailResp"
                        }
                    },
                    "400": {
                        "description": "StatusBadRequest",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    },
                    "500": {
                        "description": "StatusInternalServerError",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    }
                }
            }
        },
        "/v1/auth/logout": {
            "post": {
                "description": "Api to logout rock platform",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AUTH"
                ],
                "summary": "Logout rock platform",
                "responses": {
                    "204": {
                        "description": "StatusNoContent",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "StatusBadRequest",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    },
                    "500": {
                        "description": "StatusInternalServerError",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    }
                }
            }
        },
        "/v1/auth/pwd": {
            "post": {
                "description": "Api to update user password with secret",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AUTH"
                ],
                "summary": "Update user's password with secret",
                "parameters": [
                    {
                        "description": "JSON type input body",
                        "name": "input_body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.ResetPwdReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "StatusOK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "StatusBadRequest",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    },
                    "500": {
                        "description": "StatusInternalServerError",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    }
                }
            }
        },
        "/v1/auth/reset": {
            "post": {
                "description": "Api to create reset email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AUTH"
                ],
                "summary": "Create reset email",
                "parameters": [
                    {
                        "description": "JSON type input body",
                        "name": "input_body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.ResetUserReq"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "StatusNoContent",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "StatusBadRequest",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    },
                    "500": {
                        "description": "StatusInternalServerError",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    }
                }
            }
        },
        "/v1/roles": {
            "get": {
                "description": "api for get all roles",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ROLE"
                ],
                "summary": "Get role",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Request page number",
                        "name": "page_num",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Request page size",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Fuzzy Query(field: name)",
                        "name": "QueryField",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "StatusOK",
                        "schema": {
                            "$ref": "#/definitions/models.RolePagination"
                        }
                    },
                    "400": {
                        "description": "StatusBadRequest",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    },
                    "500": {
                        "description": "StatusInternalServerError",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "description": "api for create role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ROLE"
                ],
                "summary": "Create role",
                "parameters": [
                    {
                        "description": "JSON type input body",
                        "name": "input_body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateRoleReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "StatusCreated",
                        "schema": {
                            "$ref": "#/definitions/models.Role"
                        }
                    },
                    "400": {
                        "description": "StatusBadRequest",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    },
                    "500": {
                        "description": "StatusInternalServerError",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    }
                }
            }
        },
        "/v1/roles/{id}": {
            "get": {
                "description": "api for get an role by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ROLE"
                ],
                "summary": "Get an role by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Role ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "StatusOK",
                        "schema": {
                            "$ref": "#/definitions/models.Role"
                        }
                    },
                    "400": {
                        "description": "StatusBadRequest",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    },
                    "500": {
                        "description": "StatusInternalServerError",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    }
                }
            },
            "put": {
                "description": "api for update role description",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ROLE"
                ],
                "summary": "Update role description by id and body",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Role ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Role Description",
                        "name": "description",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "JSON type for update role description",
                        "name": "update_body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateRoleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "StatusOK",
                        "schema": {
                            "$ref": "#/definitions/models.Role"
                        }
                    },
                    "400": {
                        "description": "StatusBadRequest",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    },
                    "500": {
                        "description": "StatusInternalServerError",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    }
                }
            },
            "delete": {
                "description": "api for get an role by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ROLE"
                ],
                "summary": "Get an role by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Role ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "StatusNoContent",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "StatusBadRequest",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    },
                    "500": {
                        "description": "StatusInternalServerError",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    }
                }
            }
        },
        "/v1/users": {
            "get": {
                "description": "Api to get all users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "USER"
                ],
                "summary": "Get users",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Request page number",
                        "name": "PageNum",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Request page size",
                        "name": "PageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Fuzzy Query(field: name)",
                        "name": "QueryField",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserPagination"
                        }
                    },
                    "400": {
                        "description": "StatusBadRequest",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    },
                    "500": {
                        "description": "StatusInternalServerError",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "description": "Api to create user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "USER"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "JSON type input body",
                        "name": "input_body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.UserDetailResp"
                        }
                    },
                    "400": {
                        "description": "StatusBadRequest",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    },
                    "500": {
                        "description": "StatusInternalServerError",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    }
                }
            }
        },
        "/v1/users/{id}": {
            "get": {
                "description": "Api to get user with id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "USER"
                ],
                "summary": "Get user with id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.UserDetailResp"
                        }
                    },
                    "400": {
                        "description": "StatusBadRequest",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    },
                    "404": {
                        "description": "StatusNotFound",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    },
                    "500": {
                        "description": "StatusInternalServerError",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Api to delete user with id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "USER"
                ],
                "summary": "Delete user with id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "StatusBadRequest",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    },
                    "404": {
                        "description": "StatusNotFound",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    },
                    "500": {
                        "description": "StatusInternalServerError",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    }
                }
            }
        },
        "/v1/users/{id}/password": {
            "put": {
                "description": "Api to update user password with id and old password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "USER"
                ],
                "summary": "Update user password with id and old password",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "Id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "JSON body for update user info",
                        "name": "update_body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateUserPwdReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.UserDetailResp"
                        }
                    },
                    "400": {
                        "description": "StatusBadRequest",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    },
                    "404": {
                        "description": "StatusNotFound",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    },
                    "500": {
                        "description": "StatusInternalServerError",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.UserDetailResp": {
            "type": "object",
            "required": [
                "role_description",
                "role_version"
            ],
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2020-12-20 15:15:22"
                },
                "email": {
                    "type": "string",
                    "example": "admin_user@sensetime.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "admin_user"
                },
                "role_created_at": {
                    "type": "string",
                    "example": "2020-12-20 15:15:22"
                },
                "role_description": {
                    "type": "string",
                    "example": "description for role"
                },
                "role_id": {
                    "type": "integer"
                },
                "role_name": {
                    "type": "string"
                },
                "role_updated_at": {
                    "type": "string",
                    "example": "2020-12-20 15:15:22"
                },
                "role_version": {
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "type": "string",
                    "example": "2020-12-20 15:15:22"
                }
            }
        },
        "models.Role": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "description": "can not use LocalTime",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "description": "primary_key, AUTO_INCREMENT",
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "description": "DeletedAt LocalTime ` + "`" + `json:\"deleted_at\" gorm:\"type:timestamp;default:null\"` + "`" + `  // error\nDeletedAt LocalTime ` + "`" + `json:\"deleted_at\" gorm:\"type:timestamp null\"` + "`" + `  // error",
                    "type": "integer"
                }
            }
        },
        "models.RolePagination": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Role"
                    }
                },
                "page_num": {
                    "type": "integer"
                },
                "pages": {
                    "type": "integer"
                },
                "per_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "description": "can not use LocalTime",
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "login_block_until": {
                    "type": "string"
                },
                "login_retry_count": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "reset_secret": {
                    "type": "string"
                },
                "role_id": {
                    "description": "Role            Role       ` + "`" + `json:\"role\" gorm:\"ForeignKey:RoleId;AssociationForeignKey:Id\"` + "`" + ` // use RoleId to ForeignKey",
                    "type": "integer"
                },
                "salt": {
                    "type": "string"
                },
                "secret_expired_at": {
                    "type": "string"
                },
                "token": {
                    "description": "GitlabToken     string     ` + "`" + `json:\"gitlab_token\"` + "`" + `\nDroneToken      string     ` + "`" + `json:\"drone_token\"` + "`" + `",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "description": "DeletedAt LocalTime ` + "`" + `json:\"deleted_at\" gorm:\"type:timestamp;default:null\"` + "`" + `  // error\nDeletedAt LocalTime ` + "`" + `json:\"deleted_at\" gorm:\"type:timestamp null\"` + "`" + `  // error",
                    "type": "integer"
                }
            }
        },
        "models.UserPagination": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.User"
                    }
                },
                "page_num": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "pages": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "utils.HTTPError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error message here"
                },
                "error_code": {
                    "type": "integer",
                    "example": 50000001
                }
            }
        },
        "v1.CreateRoleReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "description for role"
                },
                "name": {
                    "type": "string",
                    "example": "admin_role"
                }
            }
        },
        "v1.CreateUserReq": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "role_id"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "admin_user@sensetime.com"
                },
                "name": {
                    "type": "string",
                    "example": "admin_user"
                },
                "password": {
                    "type": "string",
                    "example": "********"
                },
                "role_id": {
                    "description": "RoleId   *RoleIdReq ` + "`" + `json:\"role_id\" binding:\"required\"` + "`" + `  // 用顺义的这种定义，ctx.ShouldBind报错",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "v1.LoginUserInfo": {
            "type": "object",
            "required": [
                "name",
                "password"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "admin_user"
                },
                "password": {
                    "type": "string",
                    "example": "********"
                }
            }
        },
        "v1.ResetPwdReq": {
            "type": "object",
            "required": [
                "email",
                "password",
                "re_password",
                "secret"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "admin_user@sensetime.com"
                },
                "password": {
                    "type": "string",
                    "example": "********"
                },
                "re_password": {
                    "type": "string",
                    "example": "********"
                },
                "secret": {
                    "type": "string",
                    "example": "TR6UdhT7ebJOCC5N"
                }
            }
        },
        "v1.ResetUserReq": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "admin_user@sensetime.com"
                }
            }
        },
        "v1.UpdateRoleReq": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "description for role"
                }
            }
        },
        "v1.UpdateUserPwdReq": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "new_password": {
                    "type": "string",
                    "example": "********"
                },
                "old_password": {
                    "type": "string",
                    "example": "********"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
