definitions:
  utils.HTTPError:
    properties:
      error:
        example: error message here
        type: string
      error_code:
        example: 50000001
        type: integer
    type: object
  v1.RegisterUserInfo:
    properties:
      email:
        example: admin_user@sensetime.com
        type: string
      password:
        example: '********'
        type: string
      username:
        example: admin_user
        type: string
    required:
    - email
    - password
    - username
    type: object
  v1.UserDetailResp:
    properties:
      created_at:
        example: "2020-12-20 15:15:22"
        type: string
      email:
        example: admin_user@sensetime.com
        type: string
      id:
        example: 1
        type: integer
      updated_at:
        example: "2020-12-20 15:15:22"
        type: string
      username:
        example: admin_user
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/register:
    post:
      consumes:
      - application/json
      description: Api to create user
      parameters:
      - description: JSON type input body
        in: body
        name: input_body
        required: true
        schema:
          $ref: '#/definitions/v1.RegisterUserInfo'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/v1.UserDetailResp'
        "400":
          description: StatusBadRequest
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: StatusInternalServerError
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Create user
      tags:
      - USER
swagger: "2.0"
