server:
  addr: 0.0.0.0
  port: 8888  # default 8000
#  configPath: /etc/rock/config.yaml
#  https:
#    addr: 0.0.0.0
#    port: 8443
#    tls-cert-file: /opt/cert/rock.go.com.crt
#    tls-private-key-file:  /opt/cert/rock.go.com.key
  adminAuth:
    username: admin
    password: Zs/Pftkh+esjvR5SVjOYqPxaPXiDk91APmuEtuDgE9Y=
  tokenExpire: 5m  # default 10 minutes(Warning: 300 is wrong. You have to write 300s or 5m)
  kubeConfig: /etc/kubernetes/admin.conf
  login-retry-count: 5  # default 3
  login-block-duration: 5m  # default 5m
log:
  dir: /var/log/rock
  level: Debug  # default Info , you can choice Debug/Info/Warn/Error
db:
  driver: mysql
  charset: utf8mb4
  loc: Asia/Shanghai
  name: rock  # database name
  port: 3333
  host: 10.151.3.85
  user: root
  password: rock1314
tiller:
  port: 31134
email:
  user: wangyecheng465@163.com
  password: OXQBIWAMOOAYOHNV  # 163 authorization code
  smtp:
    addr: smtp.163.com
    port: 465
  secret-expire: 30m
frontend:
  domain: http://10.151.3.86:8888
drone:  # drone-server
  addr: http://10.151.3.86:8100