server:
  addr: 0.0.0.0
  port: 8080  # default 8000
#  configPath: /etc/rock/config.yaml
#  https:
#    addr: 0.0.0.0
#    port: 8443
#    tls-cert-file: /opt/cert/rock.go.com.crt
#    tls-private-key-file:  /opt/cert/rock.go.com.key
  adminAuth:
    username: admin
    password: Zs/Pftkh+esjvR5SVjOYqPxaPXiDk91APmuEtuDgE9Y=
  tokenExpire: 300  # default 300
  kubeConfig: /etc/kubernetes/admin.conf
log:
  dir: /var/log/rock
  level: Debug  # default Info , you can choice Debug、Info、Warn、Error
db:
  driver: mysql
  charset: utf8mb4
  loc: Asia/Shanghai
  name: rock  # database name
  port: 3333
  host: 10.151.3.86
  user: root
  password: rock1314
tiller:
  port: 30134